module.exports = {
  UPDATE_VIST_NAME: 'UPDATE_VIST_NAME',
  UPDATE_VIST_TITLE: 'UPDATE_VIST_TITLE',
  UPDATE_DATE_TIME: 'UPDATE_DATE_TIME',
  UPDATE_UNIQ_ID: 'UPDATE_UNIQ_ID',
  UPDATE_CAR_REGO: 'UPDATE_CAR_REGO',
  UPDATE_VIST_REASON: 'UPDATE_VIST_REASON'
}
